//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contal.Cgp.NCAS.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NCASCarReaderEditForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NCASCarReaderEditForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contal.Cgp.NCAS.Client.NCASCarReaderEditForm", typeof(NCASCarReaderEditForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string _lBuild_Text {
            get {
                return ResourceManager.GetString("_lBuild.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string _lEquipment_Text {
            get {
                return ResourceManager.GetString("_lEquipment.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface source.
        /// </summary>
        internal static string _lInterfaceSource_Text {
            get {
                return ResourceManager.GetString("_lInterfaceSource.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string _lLocked_Text {
            get {
                return ResourceManager.GetString("_lLocked.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking client IP.
        /// </summary>
        internal static string _lLockingClientIp_Text {
            get {
                return ResourceManager.GetString("_lLockingClientIp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac address.
        /// </summary>
        internal static string _lMacAddress_Text {
            get {
                return ResourceManager.GetString("_lMacAddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string _lModel_Text {
            get {
                return ResourceManager.GetString("_lModel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port SSL.
        /// </summary>
        internal static string _lPortSsl_Text {
            get {
                return ResourceManager.GetString("_lPortSsl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        internal static string _lSerial_Text {
            get {
                return ResourceManager.GetString("_lSerial.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string _lType_Text {
            get {
                return ResourceManager.GetString("_lType.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique key.
        /// </summary>
        internal static string _lUniqueKey_Text {
            get {
                return ResourceManager.GetString("_lUniqueKey.Text", resourceCulture);
            }
        }
    }
}
